apiVersion: v1
kind: Service
metadata:
  name: customer-frontend-service
  labels:
    app: customer-frontend
    service: customer-frontend
spec:
  type: NodePort
  ports:
    - targetPort : 80
      port: 80
      nodePort: 30011
      protocol: TCP
  selector:
    app: customer-frontend
    service: customer-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-frontend
  labels:
    app: customer-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: customer-frontend
  template:
    metadata:
      labels:
        app: customer-frontend
        service: customer-frontend
    spec:
      containers:
        - name: customer-frontend-container
          image: customer-frontend:latest
          imagePullPolicy: Never  # or IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          # env:
          #   - name: REACT_APP_API_URL
          #     value: http://merchants-webapi-service
          #   - name: REACT_APP_MERCHANT_KEY
          #     value: 646d246260e60733ad25d50c